add_newline = false

[character]
# success_symbol = "[⚆‿⚆](blue)"
# vicmd_symbol   = "[ಠ_ಠ](green)"
# vimcmd_symbol  = "[ಠ‿ಠ](blue)"
# success_symbol = "[ಠ_ಠ](green)"
# error_symbol   = "[ಥ_ಥ](red)"

# [directory]
# truncation_length = 4
# style = "bold lavender"
