-- vim.o.shortmess = vim.o.shortmess .. "c"
vim.g.did_load_filetypes = 0
vim.o.hidden = true
vim.o.whichwrap = "b,s,<,>,[,],h,l"
vim.o.pumheight = 10
vim.o.pumblend = 10
vim.o.fileencoding = "utf-8"
vim.o.cmdheight = 0
vim.o.splitbelow = true
vim.o.splitright = true
vim.opt.termguicolors = true
vim.o.conceallevel = 0
vim.o.showmode = false
vim.o.backup = false
vim.o.writebackup = false
-- vim.o.updatetime = 100
vim.o.timeoutlen = 250
vim.o.clipboard = "unnamedplus"
vim.o.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.o.scrolloff = 100
vim.o.sidescrolloff = 10
vim.o.mouse = "n"
vim.o.mousemodel = "extend"
vim.wo.number = true
vim.wo.relativenumber = true
vim.o.cursorline = true
vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.shiftwidth = 2
vim.o.autoindent = true
-- vim.o.smartindent = true
-- vim.o.expandtab = true
vim.o.signcolumn = "yes"
vim.o.wrap = false
vim.o.lazyredraw = true
vim.g.mapleader = " "
vim.g.completeopt = "menu,menuone,noselect,noinsert"
vim.cmd([[hi PmenuSel blend=0]])
