[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[colors.cursor]
text = "#d4d4d4"
cursor = "#d4d4d4"

[colors.normal]
black = "#1e1e1e"
red = "#f44747"
green = "#608b4e"
yellow = "#dcdcaa"
blue = "#569cd6"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#d4d4d4"

[colors.bright]
black = "#545454"
red = "#f44747"
green = "#608b4e"
yellow = "#dcdcaa"
blue = "#569cd6"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#d4d4d4"
