local ok, bufferline = pcall(require, "bufferline")

if not ok then
	return
end

-- local background = "#16161d"
local opttions = {
	numbers = "buffer_id",
	separator_style = { "", "" },
	enforce_regular_tabs = true,
}

bufferline.setup({
	options = opttions,
	-- highlights = {
	-- 	fill = {
	-- 		-- guifg = "none",
	-- 		guibg = background,
	-- 	},
	-- 	background = {
	-- 		-- guifg = "<color-value-here>",u
	-- 		guibg = background,
	-- 	},
	-- 	tab = {
	-- 		guibg = background,
	-- 	},
	-- 	tab_selected = {
	-- 		guibg = background,
	-- 	},
	-- 	tab_close = {
	-- 		guibg = background,
	-- 	},
	-- 	close_button = {
	-- 		guibg = background,
	-- 	},
	-- 	close_button_visible = {
	-- 		guibg = background,
	-- 	},
	-- 	-- close_button_selected = {
	-- 	-- 	guibg = background,
	-- 	-- },
	-- 	buffer_visible = {
	-- 		guibg = background,
	-- 	},
	-- 	-- buffer_selected = {
	-- 	-- 	guifg = normal_fg,
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- },
	-- 	diagnostic = {
	-- 		guibg = background,
	-- 	},
	-- 	diagnostic_visible = {
	-- 		guibg = background,
	-- 	},
	-- 	-- diagnostic_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- },
	-- 	hint = {
	-- 		-- guisp = "<color-value-here>",
	-- 		guibg = bg,
	-- 	},
	-- 	hint_visible = {
	-- 		-- guifg = "<color-value-here>",
	-- 		guibg = background,
	-- 	},
	-- 	-- hint_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	hint_diagnostic = {
	-- 		-- guisp = "<color-value-here>",
	-- 		guibg = background,
	-- 	},
	-- 	hint_diagnostic_visible = {
	-- 		-- guifg = "<color-value-here>",
	-- 		guibg = background,
	-- 	},
	-- 	-- hint_diagnostic_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- info = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- info_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- info_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- info_diagnostic = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- info_diagnostic_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- info_diagnostic_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- warning = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- warning_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- warning_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- warning_diagnostic = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- warning_diagnostic_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- warning_diagnostic_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = warning_diagnostic_fg,
	-- 	-- },
	-- 	-- error = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- error_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- error_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- error_diagnostic = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- error_diagnostic_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- error_diagnostic_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- 	guisp = "<color-value-here>",
	-- 	-- },
	-- 	-- modified = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- modified_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- modified_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- duplicate_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	gui = "italic",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- duplicate_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	gui = "italic",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- duplicate = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	gui = "italic",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- separator_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- separator_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- separator = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- indicator_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- },
	-- 	-- pick_selected = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- },
	-- 	-- pick_visible = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- },
	-- 	-- pick = {
	-- 	-- 	guifg = "<color-value-here>",
	-- 	-- 	guibg = "<color-value-here>",
	-- 	-- 	gui = "bold,italic",
	-- 	-- },
	-- },
})
