# (Github Dark Dimmed) Colors for Wezterm

[colors]
background = '#22272e'
foreground = '#adbac7'

cursor_bg = '#adbac7'
cursor_border = '#adbac7'
cursor_fg = '#22272e'

selection_bg = '#2e4c77'
selection_fg = '#adbac7'

ansi = [
    '#545d68',
    '#f47067',
    '#57ab5a',
    '#c69026',
    '#539bf5',
    '#b083f0',
    '#39c5cf',
    '#909dab',
]
brights = [
    '#636e7b',
    '#ff938a',
    '#6bc46d',
    '#daaa3f',
    '#6cb6ff',
    '#dcbdfb',
    '#56d4dd',
    '#cdd9e5',
]

[colors.tab_bar]
background = "#22272e"

[colors.tab_bar.active_tab]
bg_color = '#22272e'
fg_color = '#56d4dd'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#22272e'
fg_color = '#adbac7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#22272e'
fg_color = '#adbac7'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'
