local M = {}

table.insert(M, {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = false,
	-- dependencies = { "nvim-treesitter/nvim-treesitter-context" },
	cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
	opts = {
		highlight = {
			enable = true,
			disable = { "go", "lua", "sql" },
		},
		indent = { enable = true },
		ensure_installed = {
			"asm",
			"awk",
			"bash",
			"bass",
			"c",
			"cmake",
			"comment",
			"commonlisp",
			"cpp",
			"csv",
			"cuda",
			"diff",
			"dockerfile",
			"dot",
			"editorconfig",
			"elixir",
			"fish",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"glsl",
			"go",
			"gomod",
			"gosum",
			"gotmpl",
			"gowork",
			"html",
			"http",
			"javascript",
			"jq",
			"jsdoc",
			"json",
			"jsonc",
			"llvm",
			"lua",
			"luadoc",
			"luap",
			"luau",
			"make",
			"markdown",
			"nginx",
			"nix",
			"passwd",
			"pem",
			"pod",
			"powershell",
			"printf",
			"proto",
			"python",
			"readline",
			"regex",
			"rego",
			"rust",
			"scala",
			"scheme",
			"sparql",
			"sql",
			"squirrel",
			"templ",
			"terraform",
			"tmux",
			"todotxt",
			"toml",
			"tsx",
			"typescript",
			"vhs",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
			"zig",
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
		-- require("treesitter-context").setup({
		-- 	max_lines = 1,
		-- 	min_window_height = 20,
		-- 	multiline_threshold = 1,
		-- })
	end,
})

return M